[build]
  base = "frontend-next"
  command = "npm run build"
  publish = ".next"

# opcional, mas recomendado se você tiver API separada:
[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/:splat"
  status = 200
